[package]
name = "gemboy"
version = "0.1.0"
edition = "2021"

[dependencies.log]
version = "0.4.25"
features = ["std"]

[dependencies.colog]
version = "1.3.0"

[dependencies.serde_json]
version = "1.0.139"
[dependencies]
serde = { version = "1.0.218", features = ["derive"] }